version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dentalbot_app
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./templates:/app/templates
      - ./static:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["/start.sh"]
  db:
    image: postgres:15
    container_name: dentalbot_db
    environment:
      POSTGRES_USER: dentalbot
      POSTGRES_PASSWORD: dentalbot
      POSTGRES_DB: dentalbot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  nginx:
    image: nginx:stable-alpine
    container_name: dentalbot_nginx
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  postgres_data: